#!/usr/bin/env python3
"""
Convert hair_dryer.png to C array format for static compilation
Requirements: pip install pillow
"""

import os
import sys
from pathlib import Path


def make_c_identifier(name):
    """Make sure variable name is a valid C identifier."""
    var_name = "".join(ch if (ch.isalnum() or ch == "_") else "_" for ch in name)
    if not var_name:
        var_name = "img"
    if not var_name[0].isalpha() and var_name[0] != "_":
        var_name = "_" + var_name
    return var_name

def check_pillow():
    try:
        from PIL import Image
        return True
    except ImportError:
        print("Error: Pillow library not found!")
        print("Please install it using: pip install pillow")
        return False

def png_to_c_array(png_path, output_path, var_name="hair_dryer"):
    """Convert PNG image to C array format"""
    from PIL import Image
    
    # Open and convert image to RGBA
    img = Image.open(png_path).convert('RGBA')
    width, height = img.size
    pixels = list(img.getdata())
    
    # Generate C file content
    c_content = f'''/**
 * @file {var_name}.c
 * @brief Statically compiled image data for {var_name}.png
 * 
 * Auto-generated by convert_image.py
 * Image size: {width}x{height} pixels
 */

#include "lvgl/lvgl.h"

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

#ifndef LV_ATTRIBUTE_IMG_{var_name.upper()}
#define LV_ATTRIBUTE_IMG_{var_name.upper()}
#endif

/* Image data: LV_COLOR_FORMAT_ARGB8888 (byte order: BGRA) */
const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_IMG_{var_name.upper()} uint8_t {var_name}_map[] = {{
'''
    
    # Write pixel data
    bytes_per_line = 12  # 12 bytes (3 pixels) per line for readability
    byte_count = 0
    
    c_content += "    "
    for r, g, b, a in pixels:
        # LVGL lv_color32_t memory layout is B, G, R, A for ARGB8888.
        c_content += f"0x{b:02x}, 0x{g:02x}, 0x{r:02x}, 0x{a:02x}, "
        byte_count += 4
        
        if byte_count % (bytes_per_line * 4) == 0:
            c_content += "\n    "
    
    # Remove trailing comma and spaces
    c_content = c_content.rstrip(", \n") + "\n"
    
    # Calculate stride (bytes per row, should be width * 4 for ARGB8888)
    stride = width * 4
    
    c_content += f'''
}};

const lv_image_dsc_t {var_name} = {{
    .header = {{
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_ARGB8888,
        .flags = 0,
        .w = {width},
        .h = {height},
        .stride = {stride},
    }},
    .data_size = sizeof({var_name}_map),
    .data = {var_name}_map,
}};
'''
    
    # Write to file
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(c_content)
    
    print(f"✓ Successfully converted {png_path} to {output_path}")
    print(f"  Image size: {width}x{height} pixels")
    print(f"  Data size: {len(pixels) * 4} bytes ({len(pixels) * 4 / 1024:.1f} KB)")

def main():
    print("=" * 60)
    print("LVGL Image Converter - PNG to C Array")
    print("=" * 60)
    
    # Check if PIL is installed
    if not check_pillow():
        return 1

    # Default behavior: convert all PNG files in current working directory.
    # If arguments are provided, only convert the given PNG files.
    if len(sys.argv) >= 2:
        png_files = []
        for arg in sys.argv[1:]:
            input_path = Path(arg)
            if not input_path.is_absolute():
                input_path = Path.cwd() / input_path
            if input_path.suffix.lower() != ".png":
                print(f"Skip non-PNG file: {input_path}")
                continue
            png_files.append(input_path)
    else:
        png_files = sorted(
            [p for p in Path.cwd().iterdir() if p.is_file() and p.suffix.lower() == ".png"],
            key=lambda p: p.name.lower(),
        )

    if not png_files:
        print("Error: No PNG files found to convert.")
        return 1

    existing_outputs = [p.with_suffix(".c") for p in png_files if p.with_suffix(".c").exists()]
    overwrite_existing = True

    if existing_outputs:
        response = input(
            f"\nFound {len(existing_outputs)} existing .c file(s). Overwrite existing files? (y/N): "
        )
        overwrite_existing = response.lower() == 'y'

    converted_count = 0
    skipped_count = 0
    failed_count = 0

    for png_path in png_files:
        output_path = png_path.with_suffix(".c")
        var_name = make_c_identifier(png_path.stem)

        if output_path.exists() and not overwrite_existing:
            print(f"- Skipped (exists): {output_path}")
            skipped_count += 1
            continue

        try:
            print(f"\nConverting {png_path}...")
            png_to_c_array(png_path, output_path, var_name)
            converted_count += 1
        except Exception as e:
            print(f"\n✗ Error during conversion of {png_path}: {e}")
            import traceback
            traceback.print_exc()
            failed_count += 1

    print("\n" + "=" * 60)
    print("Conversion Summary")
    print("=" * 60)
    print(f"Converted: {converted_count}")
    print(f"Skipped:   {skipped_count}")
    print(f"Failed:    {failed_count}")

    if failed_count > 0:
        return 1

    print("\n✓ Conversion completed successfully!")
    print("\nNext steps:")
    print("  1. Compile in Release mode: cmake -B build -DCMAKE_BUILD_TYPE=Release")
    print("  2. Build: cmake --build build --config Release")
    return 0

if __name__ == "__main__":
    sys.exit(main())

